version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
  hostname: "rabbit1"
  ports: 
    - "15672:15672"
    - "5672:5672"
  labels: 
    NAME: "some-rabbit"
  sqlserver:
    image: "mcr.micorsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pass"
      MSSQL_PID: "Express"
    Ports:
      - "1433:1433"

